### ISSUE TITLE
QUESTION: Setting folder for WriteFile

### ISSUE THREAD

**Issue by tinjaw** [LuisEnMarroquin/json-as-xlsx#10]
I am using this in an Electron app. Right now, there is no way, by existing API, to choose the directory where the file gets written to -- so it ends up in the executables folder. Is there a way to modify this code to accept a path that the file will save to?

**Comment by LuisEnMarroquin** [comment]
Hi, you can try setting a 4th argument as `false` to return a buffer and then use `fs.writeFileSync` to set a custom path

```js
const { writeFileSync } = require('fs')
const xlsx = require('json-as-xlsx')

var buffer = xlsx(columns, content, settings, false)
const homedir = require('os').homedir()
writeFileSync(`${homedir}/Downloads/mySheet.xlsx`, buffer)
```

I tried to add a move native way, but I don't know a lot about Electron

Tell me if it works

**Comment by tinjaw** [comment]
That works great. Thank you.
