### ISSUE TITLE
Duplicate column definitions cause ugly error

### ISSUE THREAD

**Issue by phil-w** [LuisEnMarroquin/json-as-xlsx#17]
This works great and I'm using it a lot.

One thing it doesn't like one bit is duplicate column definitions, which result in:

```
index.js:43 Uncaught (in promise) TypeError: Cannot read property 'v' of undefined
    at eval (index.js:43)
    at Array.forEach (<anonymous>)
...
```

**Comment by LuisEnMarroquin** [comment]
Hi, thanks for reporting the issue

By duplicate column definitions you mean the column titles? can you provide the code that's failing?

**Comment by phil-w** [comment]
**My error** was that I'd duplicated the column label (which are simply UI text in my case) by accident in my static definition, so it's my defect not yours. I don't think your code should identify the issue particularly, but maybe just close this and if someone else has the error ... it may help them find it?

Here's how to repeat it:
```
xlsx.default(
  [{  sheet: 'Adults',
      columns: [
            { label: 'Age', value: 'age' },
            { label: 'Age', value: 'age' }, // Duplicate "label" value causes throw.
      ],
      content: [ { user: 'Andrea', age: 20, } ]
  }],
  {sheetName: 'Table Data', fileName:fileName, extraLength: 3, writeOptions:{}});
```

**Comment by LuisEnMarroquin** [comment]
Okay, no problem, I'll close the issue
