### ISSUE TITLE
Cannot read 'v' of undefined

### ISSUE THREAD

**Issue by matiaslopezd** [LuisEnMarroquin/json-as-xlsx#18]
Hi, @LuisEnMarroquin I think I discover a bug here:

https://github.com/LuisEnMarroquin/json-as-xlsx/blob/6cdd620200fc9b6d45a70ba5740d6a5ccbdc5e1a/index.ts#L50

The source of this error it's here:

https://github.com/LuisEnMarroquin/json-as-xlsx/blob/6cdd620200fc9b6d45a70ba5740d6a5ccbdc5e1a/index.ts#L34

This is happening because the `while` loop end when `whileLoop` is smaller than `excelColumns`, but the problem is you're adding `1` to `excelColumns`, so in the final loop `newSheet` is `undefined`.

I suggest removing the `1` or better use the length of `columns` key of  `data`. 

I'm working on a refactor, I believe the code can be improved in terms of readability. (I'm no fan of Typescript)

**Comment by LuisEnMarroquin** [comment]
Hi @matiaslopezd, sorry for the late reply, I was too busy at work

Released latest version `2.1.0` that includes:

I did a refactor to improve readability, but I want to keep TS, I think it helps me a lot :c
* Removed `excelColumns`, `whileLoop` and `in2` to only use `excelIndexes.forEach`
* Added `ts-standard` as a linter in `package.json` and `.vscode/settings.json` 
* Created `CONTRIBUTING.md` to give instructions about running the project

I think that optional-chain `newSheet['!cols']?.push(size)` will solve the issue `Cannot read 'v' of undefined`

Feel free to reopen this issue if the problem wasn't solved
