### ISSUE TITLE
Generate xlsx with password

### ISSUE THREAD

**Issue by jacksonsilvadev** [LuisEnMarroquin/json-as-xlsx#19]
Hey,

Have some option to encrypt file with password?

**Comment by LuisEnMarroquin** [comment]
Hi there

Currently no, but is supported in the main library [xslx](https://www.npmjs.com/package/xlsx)

![image](https://user-images.githubusercontent.com/35376824/134580559-5bc69234-2911-4aa1-ad58-efe8ccf6ebe3.png)
