### ISSUE TITLE
Wrong column widths when creating more than 24 columns

### ISSUE THREAD

**Issue by elyse0** [LuisEnMarroquin/json-as-xlsx#22]
Currently we first get all column letters ('A', 'B' ,... 'Z', 'AA', 'BB',... ) and then filter the cells by checking their first letter with the 'column letters'.

If 'columnLetters' is "AA" and 'cell' is "AA1", it wouldn't filter it because the first letter of the cell is not the same as the columnLetters ("A" =! "AA") and we wouldn't get the appropriate column width.

https://github.com/LuisEnMarroquin/json-as-xlsx/blob/5d5578c96c2847dd427d3f45beaaa22a0a30c5a3/index.ts#L36-L59

My first idea is to also verify the second letter but maybe there's a better way to do it 🤔

```diff
const columnCells: string[] = Object.keys(worksheet).filter((cell) => { 
-       return cell.charAt(0) === column
+       return cell.charAt(0) === column || cell.slice(0, 2) === column
     }) 
```

**Comment by LuisEnMarroquin** [comment]
Probably it's the easier way to do it, I added the change to https://github.com/LuisEnMarroquin/json-as-xlsx/commit/bbc93716abee8ccc6b22768d1da828f95b4bf46e and released version 2.2.3

Thanks 🤗
