### ISSUE TITLE
Decrease package size

### ISSUE THREAD

**Issue by elyse0** [LuisEnMarroquin/json-as-xlsx#25]
When I create a 'build' version of my Vue app ,I usually get the alert 'entry point size limit' but I kept ignoring it. 😆 

But today I decided to look into why... so I used 'vue-cli-service build --report' and got this image

![image](https://user-images.githubusercontent.com/26639800/142314538-94a723f6-cee1-4b88-aee7-7b336b673b64.png)

I don't know why is that big, we're not importing all functions of that package... 🤔  

Any ideas on how to decrease the package size?

**Comment by elyse0** [comment]
I used route lazy-loading and helped a lot but I still think its size is huge 🤔 

![image](https://user-images.githubusercontent.com/26639800/142452917-aeae6cd6-db7d-4ad7-b918-69ea2f16c6d2.png)

**Comment by LuisEnMarroquin** [comment]
I think it won't be possible currently because `xlsx` library in on a single file, so we will have to import it complete

![image](https://user-images.githubusercontent.com/35376824/142797165-e991d8d4-db59-4c70-a6ac-29195480061e.png)

Otherwise we could import the functions like this

```ts
import writeFile from 'xlsx/writeFile'
```

**Comment by LuisEnMarroquin** [comment]
Another idea is to use something like @vercel/ncc so we can bundle everything to a single file and we won't need to add `xlsx` as a `devDevendency`. Do you think that's a good idea? 🤔

**Comment by elyse0** [comment]
> ```ts
> import writeFile from 'xlsx/writeFile'
> ```

Yeah, I think this could help a lot because they've recently added support for **ES modules** 😮 . See: https://github.com/SheetJS/sheetjs/issues/2033

The only detail is that we need to import from "**xlsx.mjs**" 

I will try it and see if it works 🐞

**Comment by elyse0** [comment]
> Another idea is to use something like @vercel/ncc so we can bundle everything to a single file and we won't need to add `xlsx` as a `devDevendency`. Do you think that's a good idea? thinking

I think its a good idea! If someone is using this package, probably just needs to export **json-as-excel** and doesn't need all of the functions of 'xlsx'  🤔

**Comment by elyse0** [comment]
I got these stats using ```vue-cli-service build --report``` for the vue app that you deploy

- Current stat size ```xlsx``` (1.44 MB)

![image](https://user-images.githubusercontent.com/26639800/142905351-4efe4298-582e-4617-a611-e466901600c2.png)

- Stat size using ```xlsx/xlsx.mjs``` (798 KB)

![image](https://user-images.githubusercontent.com/26639800/142905528-14217d23-8ad8-44d9-98eb-ca5352a26360.png)

- Stat size using ```xlsx/dist/xlsx.mini.min``` (222 KB)

![image](https://user-images.githubusercontent.com/26639800/142905698-cfdc4fff-55ec-42ec-8849-380b366b8587.png)

The smallest is ```xlsx.mini.min.js```, all tests are passing but I still don't know which functionalities could be missing 🤔 

Would be interesting to know if @vercel/ncc can improve it ^-^

**Comment by LuisEnMarroquin** [comment]
Hi there, I created branch `vercel-ncc` with ncc demo, it looks that's not the way we should go (925 KiB)

```shell
$ npm run build && npx vue-cli-service build --report

> json-as-xlsx@2.2.5 build
> rm -f index.js && npx -p @vercel/ncc ncc build index.ts --out . --minify

ncc: Version 0.32.0
ncc: Compiling file index.js into CJS
ncc: Using typescript@4.5.2 (local user-provided)
983kB  index.js
983kB  [5698ms] - ncc 0.32.0

-  Building for production...
 WARNING  Compiled with 3 warnings4:35:47 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/app.f2d36b97.js (925 KiB)
  js/chunk-vendors.6c6cfda0.js (693 KiB)

 warning

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.58 MiB)
      js/chunk-vendors.6c6cfda0.js
      css/app.b50d6a18.css
      js/app.f2d36b97.js


 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                 Size               Gzipped

  dist\js\app.f2d36b97.js              924.59 KiB         329.72 KiB
  dist\js\chunk-vendors.6c6cfda0.js    693.15 KiB         210.29 KiB
  dist\css\app.b50d6a18.css            0.30 KiB           0.23 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

Probably the best idea will be to use `xlsx.mini.min.js`, do you agree?

A question, how do you generate the stats as images? 🤔

**Comment by elyse0** [comment]
Yeah, it's the smallest one.  I'll make that PR 😄 

I use ```vue-cli-service build --report``` 🐛  It creates ```report.html``` inside **dist/**  that I can open in my browser

**Comment by elyse0** [comment]
Typescript is complaining because 'xlsx.mini.min' doesn't have types 😠  The simple fix is copying the types from xlsx and create a module, but I will search if there's a cleaner solution

![image](https://user-images.githubusercontent.com/26639800/143525730-e3e24218-845a-4da5-b337-fef88e25c22e.png)

**Comment by elyse0** [comment]
> Typescript is complaining because 'xlsx.mini.min' doesn't have types angry The simple fix is copying the types from xlsx and create a module, but I will search if there's a cleaner solution
> 
> ![image](https://user-images.githubusercontent.com/26639800/143525730-e3e24218-845a-4da5-b337-fef88e25c22e.png)

Long story short, we need to copy them 😞

**Comment by LuisEnMarroquin** [comment]
Well, if it does the trick is fine🤗

I'll close this and merge the PR, thanks 💝

**Comment by Arashatami** [comment]
> > Typescript is complaining because 'xlsx.mini.min' doesn't have types angry The simple fix is copying the types from xlsx and create a module, but I will search if there's a cleaner solution
> > ![image](https://user-images.githubusercontent.com/26639800/143525730-e3e24218-845a-4da5-b337-fef88e25c22e.png)
> 
> Long story short, we need to copy them 😞

Please share 

> > Typescript is complaining because 'xlsx.mini.min' doesn't have types angry The simple fix is copying the types from xlsx and create a module, but I will search if there's a cleaner solution
> > ![image](https://user-images.githubusercontent.com/26639800/143525730-e3e24218-845a-4da5-b337-fef88e25c22e.png)
> 
> Long story short, we need to copy them 😞

Please share xlsx.mini.min.d.ts
