### ISSUE TITLE
exposing workbook with callback

### ISSUE THREAD

**Issue by QuadTriangle** [LuisEnMarroquin/json-as-xlsx#27]
can you please add a callback to `xlsx` to access workbook
e.g 

```js
function xlsx (jsonSheets: IJsonSheet[], settings: ISettings = {}, callback): Buffer | undefined {
 ........
 })

  if (callback) callback(workbook);
  return writeWorkbook(workbook, settings)
}
```

It will help to set filter to a worksheet and calculated cache value for Excel formula

```js
    var buffer = xlsx(data, settings, function(workbook) {
        XLSX_CALC(workbook);
        workbook.Sheets.mysheet['!autofilter'] = {ref: 'A1:H5'};
    })
```

**Comment by LuisEnMarroquin** [comment]
Hi, does this work? https://github.com/LuisEnMarroquin/json-as-xlsx/blob/c5414d5a6d1205c6796cfa7830543d21455dffd3/index.ts#L99

**Comment by QuadTriangle** [comment]
working as expected ( `please remove return  statement` )

Thank you

**Comment by LuisEnMarroquin** [comment]
Released version `2.3.2`

**Comment by QuadTriangle** [comment]
@LuisEnMarroquin 

I wanted a minimum change to the existing code. 
e.g

```js
let xlsx = require('./json-as-xlsx')
let XLSX_CALC = require('xlsx-calc')

let data = [{
    sheet: 'mysheet',
    columns: [
        { label: 'Item', value: 'item' },
        { label: 'Price', value: 'price' },
    ],
    content: [
        { item: 'foo', price: 20 },
        { item: 'bar', price: 30 },
        { item: 'foo', price: 15 },
        {
            item: 'Total',
            price: {
                t: 'n',
                f: `SUM(B2:B4)`,
                v: 0
            }
        },
    ]
}]

let settings = {
    fileName: 'mysheet',
    extraLength: 3,
    writeOptions: {}
}

xlsx(data, settings, function(workbook) {
    // pre-calculate Excel formula value so that the value can be accessed from js or from Excel protected view
    XLSX_CALC(workbook);

    var filter = {ref: 'A1:B4'}; // filter range
    workbook.Sheets.mysheet['!autofilter'] = filter;
})
```

I have only added a callback to access the workbook.

you have replaced `return` with `else` which performs the same functionality. If I use a callback to access the workbook, it returns before writing the workbook. Unfortunately, now I will have to implement `writeWorkbook` function myself. I just wanted to access workbook without changing anything.

```ts
const xlsx = (jsonSheets: IJsonSheet[], settings: ISettings = {}, callback: any = false): Buffer | undefined => {
  if (jsonSheets.length === 0) return

  const workbook = utils.book_new() // Creating a workbook, this is the name given to an Excel file
  jsonSheets.forEach((actualSheet, actualIndex) => {
    const worksheet = getWorksheet(actualSheet, settings)
    const worksheetName = actualSheet.sheet ?? `Sheet ${actualIndex + 1}`
    utils.book_append_sheet(workbook, worksheet, worksheetName) // Add Worksheet to Workbook
  })

  if (callback !== false) callback(workbook)
  writeWorkbook(workbook, settings)
}
```

**Comment by LuisEnMarroquin** [comment]
This change is okay? https://github.com/LuisEnMarroquin/json-as-xlsx/commit/c372e0382ea599af9dfc997ffe32548e9417b818

**Comment by QuadTriangle** [comment]
Yes. Now, it works without any changes. Thanks for your time and quick responses 😊

**Comment by XCanG** [comment]
@LuisEnMarroquin don't mind if I ask a simple question? I'm trying to paste a link in a table not as a text, but as a clickable link. I don't know the proper syntax or what is documentation for this and I only find this post somehow vagualy referencing this.

I need to paste a typical formula `=HYPERLINK("URL", "URL")`, from example here I wrote column like this:
```js
{label: "URL", value: (row) => ({t: row.url, f: `HYPERLINK("${row.url}", "${row.url}")`, v: row.url})}
```

But doing it this way freezes Excel whenever I click on the cell with URL. What would be the syntax?
