### ISSUE TITLE
Target path

### ISSUE THREAD

**Issue by virgaux** [LuisEnMarroquin/json-as-xlsx#36]
Hi, 

Is there any option to have a target path/directory where to save the file? Also, can you also include all the options that can be done in settings? It is not in the README apprently. 

Thanks!

**Comment by elyse0** [comment]
Hi !🐞

I suppose you're running it on `node`, isn't it?

If that's the case, you can pass the full path in the `fileName` config

For example:
```js
import path from "path"

const outputPath = path.resolve(__dirname, "tmp", "output.xlsx")

xlsx(jsonSheets, {fileName: outputPath, writeOptions: {type: 'file'}})
```
This code saves the `output.xlsx` file inside the `tmp` project folder (**Note:** The folder must already exist)

**Comment by virgaux** [comment]
thanks!
