### ISSUE TITLE
[question] Is there a way to set what format a column has?

### ISSUE THREAD

**Issue by joneldiablo** [LuisEnMarroquin/json-as-xlsx#37]
Is there a way to set what format a column has?
for example:
```
columns:[
  { label: 'Amount', value: 'amount', format:'Currency' },
  { label: 'Size', value: 'size', format:'Number' }
]
```
thanks!

**Comment by elyse0** [comment]
Hi ! 🐞

No, cell formats are not currently supported. 

SheetJs already [supports it](https://github.com/SheetJS/sheetjs#common-spreadsheet-format), so it doesn't seem too hard to implement and overall would be a nice feature to have.

If you want, you can open a PR for this or maybe someone else could do it in the future

**Comment by LuisEnMarroquin** [comment]
Hello there, @elyse0 added support for it!

You can use version `2.4.0`
