### ISSUE TITLE
Bug: Wrong calculated width for many columns

### ISSUE THREAD

**Issue by kachaj7** [LuisEnMarroquin/json-as-xlsx#40]
Hi,

the comparison in index.ts at line 93 is made wrong. 

`return cell.charAt(0) === column || cell.slice(0, 2) === column`

Example: function starts with column A, then filter gets columns like AA, AB, AC, etc.

Better is to use:

`return cell.replace(/[0-9]/g, '') === column`

**Comment by elyse0** [comment]
Yep, that's much better! 🐞  I remember thinking about this in #22 , thanks for fixing it 😄 

Can you open a Pull Request to fix this?

**Comment by LuisEnMarroquin** [comment]
Great, thank you

It should be included on version `2.4.1`
