### ISSUE TITLE
Not saving using the fileName mentioned in ISettings

### ISSUE THREAD

**Issue by arcp10** [LuisEnMarroquin/json-as-xlsx#51]
const settings: ISettings = {
            fileName: 'abc_results.xlsx', 
            extraLength: 2, 
            writeOptions: {}
        };
It gets a random file name on download and no file type. Is there some other setting that I am missing? Or is there any way I can tweak the return object and change the file name before downloading the attachment. Any help is highly appreciated I spent enough time on this to figure out but in vain. Thank you!!

**Comment by elyse0** [comment]
Can you give more details about your use case? 

In any case, here are some examples:
- Using with Express: https://github.com/LuisEnMarroquin/json-as-xlsx/blob/main/examples/express/server.ts
- Using with Vue.js: https://github.com/LuisEnMarroquin/json-as-xlsx/blob/main/examples/vue-app/App.vue

**Comment by LuisEnMarroquin** [comment]
I was also unable to reproduce the issue, it's still hapenning with latest version?

It can be reopen it if it still happens
