### ISSUE TITLE
How can i export with rowSpan and colSpan ? example demo 

### ISSUE THREAD

**Issue by vuboi** [LuisEnMarroquin/json-as-xlsx#53]

**Comment by webmasterz2022** [comment]
I need this too pls, anybody have the samples?

**Comment by elyse0** [comment]
It's not supported directly, but you can do it using the callback

```js
import jsonAsXlsx, { IJsonSheet, WorkBook, utils } from 'json-as-xlsx'

const create = () => {
    const todaySells = [{
        'name': 'Football jersey',
        'size': 'S',
        'quantity': 4,
    }, {
        'name': 'Football jersey',
        'size': 'M',
        'quantity': 1,
    }, {
        'name': 'Football jersey',
        'size': 'XL',
        'quantity': 2,
    }, {
        'name': 'Black skirt',
        'size': 'S',
        'quantity': 10,
    }, {
        'name': 'Black skirt',
        'size': 'M',
        'quantity': 3,
    }]

    const jsonSheets: IJsonSheet[] = [{
        sheet: '2022-11-27',
        columns: [{
            label: "Item's name",
            value: 'name'
        }, {
            label: "Item's size",
            value: 'size'
        }, {
            label: 'Items sold',
            value: 'quantity'
        }],
        content: todaySells
    }]

    jsonAsXlsx(jsonSheets, {fileName: 'daily-report'}, (workbook: WorkBook) => {
        const sheetNames = workbook.SheetNames;
        if (!sheetNames.length) {
            return;
        }

        sheetNames.forEach((sheetName: string) => {
            const worksheet = workbook.Sheets[sheetName];

            worksheet['!merges'] = [
                utils.decode_range('A2:A4'),
                utils.decode_range('A5:A6')
            ];
        });
    })
}

create()
```

But usually we don't know the range string that we want to merge, so you can use an object that specifies the Start (row, colum) and End(row, column) that you can programmatically create.

```js
interface WorksheetRange {
    s: {
        r: number,
        c: number
    },
    e: {
        r: number,
        c: number
    }
}

...

jsonAsXlsx(jsonSheets, {fileName: 'daily-report'}, (workbook: WorkBook) => {
        const sheetNames = workbook.SheetNames;
        if (!sheetNames.length) {
            return;
        }

        sheetNames.forEach((sheetName: string) => {
            const worksheet = workbook.Sheets[sheetName];

            const mergeRanges: WorksheetRange[] = [{
                s: {
                    r: 1,
                    c: 0,
                },
                e: {
                    r: 3,
                    c: 0,
                },
            }, {
                s: {
                    r: 4,
                    c: 0,
                },
                e: {
                    r: 5,
                    c: 0,
                },
            }];

            worksheet["!merges"] = mergeRanges;
        });
    })
```

![image](https://user-images.githubusercontent.com/26639800/204123435-e956771b-0bef-4ada-8bf6-fc97c5d73b4c.png)

**Comment by vuboi** [comment]
> It's not supported directly, but you can do it using the callback
> 
> ```js
> import jsonAsXlsx, { IJsonSheet, WorkBook, utils } from 'json-as-xlsx'
> 
> const create = () => {
>     const todaySells = [{
>         'name': 'Football jersey',
>         'size': 'S',
>         'quantity': 4,
>     }, {
>         'name': 'Football jersey',
>         'size': 'M',
>         'quantity': 1,
>     }, {
>         'name': 'Football jersey',
>         'size': 'XL',
>         'quantity': 2,
>     }, {
>         'name': 'Black skirt',
>         'size': 'S',
>         'quantity': 10,
>     }, {
>         'name': 'Black skirt',
>         'size': 'M',
>         'quantity': 3,
>     }]
> 
>     const jsonSheets: IJsonSheet[] = [{
>         sheet: '2022-11-27',
>         columns: [{
>             label: "Item's name",
>             value: 'name'
>         }, {
>             label: "Item's size",
>             value: 'size'
>         }, {
>             label: 'Items sold',
>             value: 'quantity'
>         }],
>         content: todaySells
>     }]
> 
>     jsonAsXlsx(jsonSheets, {fileName: 'daily-report'}, (workbook: WorkBook) => {
>         const sheetNames = workbook.SheetNames;
>         if (!sheetNames.length) {
>             return;
>         }
> 
>         sheetNames.forEach((sheetName: string) => {
>             const worksheet = workbook.Sheets[sheetName];
> 
>             worksheet['!merges'] = [
>                 utils.decode_range('A2:A4'),
>                 utils.decode_range('A5:A6')
>             ];
>         });
>     })
> }
> 
> create()
> ```
> 
> But usually we don't know the range string that we want to merge, so you can use an object that specifies the Start (row, colum) and End(row, column) that you can programmatically create.
> 
> ```js
> interface WorksheetRange {
>     s: {
>         r: number,
>         c: number
>     },
>     e: {
>         r: number,
>         c: number
>     }
> }
> 
> ...
> 
> jsonAsXlsx(jsonSheets, {fileName: 'daily-report'}, (workbook: WorkBook) => {
>         const sheetNames = workbook.SheetNames;
>         if (!sheetNames.length) {
>             return;
>         }
> 
>         sheetNames.forEach((sheetName: string) => {
>             const worksheet = workbook.Sheets[sheetName];
> 
>             const mergeRanges: WorksheetRange[] = [{
>                 s: {
>                     r: 1,
>                     c: 0,
>                 },
>                 e: {
>                     r: 3,
>                     c: 0,
>                 },
>             }, {
>                 s: {
>                     r: 4,
>                     c: 0,
>                 },
>                 e: {
>                     r: 5,
>                     c: 0,
>                 },
>             }];
> 
>             worksheet["!merges"] = mergeRanges;
>         });
>     })
> ```
> 
> ![image](https://user-images.githubusercontent.com/26639800/204123435-e956771b-0bef-4ada-8bf6-fc97c5d73b4c.png)

I will try, thanks you so much !!!

**Comment by LuisEnMarroquin** [comment]
Question solved by [elyse0](https://github.com/elyse0) thanks!
