### ISSUE TITLE
Writing options link is broken?

### ISSUE THREAD

**Issue by enigmablue** [LuisEnMarroquin/json-as-xlsx#54]
https://github.com/SheetJS/sheetjs#writing-options is broken?

I'm trying to find out how to wrap a column.

**Comment by LuisEnMarroquin** [comment]
@enigmablue It [used to work](https://github.com/SheetJS/sheetjs/blob/88225f5fd565648a36a299d9628722c023af47a5/README.md), sheetjs team changed the docs location

**Comment by LuisEnMarroquin** [comment]
@enigmablue This is the new one: https://docs.sheetjs.com/docs/api/write-options

The README.md is also updated with the new link
