### ISSUE TITLE
Package homepage is not working

### ISSUE THREAD

**Issue by joaoarieira** [LuisEnMarroquin/json-as-xlsx#55]
Hi.
https://xlsx.marroquin.dev is not working at all.

**Comment by joaoarieira** [comment]
Those aren't working either:
https://xlsx.pages.dev/
https://xlsx.luismarroquin.com/

**Comment by LuisEnMarroquin** [comment]
Hi, it should be fixed when https://github.com/LuisEnMarroquin/json-as-xlsx/pull/59 is merged
