### ISSUE TITLE
json-as-xlsx module not working in Vue development mode

### ISSUE THREAD

**Issue by tenzint** [LuisEnMarroquin/json-as-xlsx#56]
Issue: I am unable to use this module in development mode, it works in production mode. I am simply using `import xlsx from "json-as-xlsx`

Error message in chrome console: 
`vue-router.mjs:3451 SyntaxError: The requested module '/node_modules/.pnpm/json-as-xlsx@2.4.6/node_modules/json-as-xlsx/src/index.js' does not provide an export named 'default' (at index.vue:5:1)`

Information:
Node v16.18.0
npm 8.19.2
pnpm 7.14.0
"json-as-xlsx": "^2.4.6",
"vue": "^3.2.40",

**Comment by elyse0** [comment]
I had a similar issue using vue 2 + vite, can you try using https://www.npmjs.com/package/@elyse0/json-as-xlsx ?

If that works, we will need to add an ESM version for this package

**Comment by LuisEnMarroquin** [comment]
Hi @tenzint and @elyse0 I was getting the same issue with Vite + React

And was able to fix it by adding this to my `vite.config.ts`

```json
optimizeDeps: {
  include: ["json-as-xlsx"],
},
```

Let me know if it works for you

**Comment by LuisEnMarroquin** [comment]
Not sure if it's still happening, feel free to reopen if it's still an issue
