### ISSUE TITLE
Column Width

### ISSUE THREAD

**Issue by rolexta** [LuisEnMarroquin/json-as-xlsx#58]
Hallo, can we set width for a column?
Thank you

**Comment by LuisEnMarroquin** [comment]
It's not possible to explicitly set the column width for each column, it is calculated automatically but you can set a bigger size for all columns by sending `{ extraLength: <number> }` as the second argument when calling `xlsx`

This example creates 3 `xlsx` files with different column width sizes:

```js
const xlsx = require("json-as-xlsx");

function generateColumns(accumulator, element) {
  const keys = Object.keys(element);
  keys.forEach((key) => !accumulator.includes(key) && accumulator.push(key));
  return accumulator;
}

const data = [
  { Name: "Luis", Age: 23 },
  { Name: "Monse", Age: 22 },
];
const keys = data.reduce(generateColumns, []);
const columns = keys.map((key) => ({ label: key, value: key }));

xlsx([{ sheet: "Test", columns: columns, content: data }], {
  fileName: "TestFile-1",
});

xlsx([{ sheet: "Test", columns: columns, content: data }], {
  fileName: "TestFile-2",
  extraLength: 5,
});

xlsx([{ sheet: "Test", columns: columns, content: data }], {
  fileName: "TestFile-3",
  extraLength: 50,
});
```

<img width="543" alt="image" src="https://user-images.githubusercontent.com/35376824/224576533-f61d93b7-84b2-4e2f-80aa-36cf687214f0.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/35376824/224576553-476b15ed-1799-4aa3-a53a-846dc45ed978.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/35376824/224576560-b541d6e4-7a8b-4c91-a2c0-dd043cc09014.png">

Related to https://github.com/LuisEnMarroquin/json-as-xlsx/issues/2
