### ISSUE TITLE
Receiving file without downloading

### ISSUE THREAD

**Issue by brian-sa** [LuisEnMarroquin/json-as-xlsx#60]
Hi, I'm wondering if it is possible to use this library to generate the excel file but not initiate the download?
Looking to add the generated file to a zip file and download that instead.

**Comment by elyse0** [comment]
Yep, you can get the file to an ArrayBuffer setting writeOptions.type to "buffer".

This is how its used in the Express demo
https://github.com/LuisEnMarroquin/json-as-xlsx/blob/main/packages/demo-express/src/server.ts

```js
const settings: ISettings = {
  writeOptions: {
    type: "buffer",
    bookType: "xlsx",
  },
}

 const buffer = xlsx(data, settings)
```

**Comment by LuisEnMarroquin** [comment]
Thanks @elyse0 I am closing this question
