### ISSUE TITLE
Vulnerability found on latest version of json-as-xlsx

### ISSUE THREAD

**Issue by pinceladasdaweb** [LuisEnMarroquin/json-as-xlsx#74]
### Summary

There are vulnerability found in the json-as-xlsx version 2.5.3 due to xlsx.

<img width="590" alt="Captura de Tela 2023-04-29 às 18 25 02" src="https://user-images.githubusercontent.com/814325/235324876-75b94541-f465-4750-8b77-af8402cf23bd.png">

###  Possible Solution

Updating the xlsx dependency to patched version: 0.19.3

### Context

More information about CVE is here: https://github.com/advisories/GHSA-4r6h-8v6p-xvw6

**Comment by githubjosh** [comment]
please fix this. simply update your dependencies to use the CDN - https://github.com/SheetJS/sheetjs/issues/2822#issuecomment-1563952655

```
"dependencies" : {
  "xlsl" : "https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz"
}
```

**Comment by piotrzaborow** [comment]
@LuisEnMarroquin can you help with fix the issue?

PR #77 for this is already published and waiting for merging.

**Comment by pinceladasdaweb** [comment]
@LuisEnMarroquin Please, accept the PR.

**Comment by LuisEnMarroquin** [comment]
Hello there, sorry, it was a long time since I modified this project

It should be solved by this PR: https://github.com/LuisEnMarroquin/json-as-xlsx/pull/88

Can you help me review it? Thanks in advance

**Comment by pinceladasdaweb** [comment]
Thank you for this fix @LuisEnMarroquin.
