### ISSUE TITLE
null in content

### ISSUE THREAD

**Issue by silencechow** [LuisEnMarroquin/json-as-xlsx#8]
I have some value in content is null, it will case error in index.js line 34.
example:
`
let content = [
    { name: 'test 1', 'gender': null, email: 'test@example.com' },
    { name: 'test 2', gender: 'M', email: 'test2@example.com' }
];
`

**Comment by LuisEnMarroquin** [comment]
Hi, thanks for your feedback, I think it's now fixed, just upgrade to version `1.1.1`

I'll close this issue, feel free to open a new one if the problem persists
