### ISSUE TITLE
fix: we should be able to use the type `null` with `IContent`

### ISSUE THREAD

**Issue by cjxe** [LuisEnMarroquin/json-as-xlsx#80]
I made a PR for it
- https://github.com/LuisEnMarroquin/json-as-xlsx/pull/79

**Comment by LuisEnMarroquin** [comment]
@cjxe I was going to release a new version of this package but I noticed this type error: https://github.com/LuisEnMarroquin/json-as-xlsx/actions/runs/5904533569/job/16016815345?pr=81

<img width="948" alt="image" src="https://github.com/LuisEnMarroquin/json-as-xlsx/assets/35376824/ce7f125a-e347-408f-b794-7519af64203b">

**Comment by cjxe** [comment]
I made [another PR](https://github.com/LuisEnMarroquin/json-as-xlsx/pull/83) where I:
- fixed this error
- explained the steps to recover the repo

**Comment by cjxe** [comment]
fixed!

**Comment by LuisEnMarroquin** [comment]
@cjxe Thank you 🙌

**Comment by cjxe** [comment]
Thank you too Luis! :)
