### ISSUE TITLE
Using json-as-xlxs not for download xlxs

### ISSUE THREAD

**Issue by tisufa** [LuisEnMarroquin/json-as-xlsx#97]
Hello, how to using json-as-xlxs but i don't want to download it. I just want to consume the result as buffer or file to print it without download.

**Comment by LuisEnMarroquin** [comment]
hello, this example shows how to handle it as buffer: https://github.com/LuisEnMarroquin/json-as-xlsx/blob/main/packages/demo-express/src/server.ts

**Comment by tisufa** [comment]
> hello, this example shows how to handle it as buffer: https://github.com/LuisEnMarroquin/json-as-xlsx/blob/main/packages/demo-express/src/server.ts

Thank you so much, it's really helpfull
